version: '3'

services:
  # Backend service
  backendnode:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - mongonode

  # Frontend service
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - backendnode

  # MongoDB service
  mongonode:
    image: "mongo:latest"
    ports:
      - "27018:27017"











